### ISSUE TITLE
[BUG] Saucybot not properly embedding/triggering, unsure what exactly causes it

### ISSUE THREAD

**Issue by LatGeek** [Sn0wCrack/saucybot-discord#25]
This has been happening for a couple days now, the embed will be in a non-english language or a generic "tweet" and the bot won't pick it up. I've seen it work just fine with some links and not with others, can't find a pattern for it.
![Discord_j8gCVkN4TB](https://user-images.githubusercontent.com/22866186/170090742-50a32ac4-a8a5-4ab5-b2d9-77d19c76b6d1.png)
![Discord_RwogjuNIuj](https://user-images.githubusercontent.com/22866186/170090744-c1651239-990c-4a81-9740-1ab0ffd5c124.png)
![Discord_AnSJqxSYhd](https://user-images.githubusercontent.com/22866186/170090745-40b14d17-f15d-4f36-a9bb-0b9cf081b8b9.png)
![Discord_Cn2lSKxkYg](https://user-images.githubusercontent.com/22866186/170090746-25aa80c6-4a90-41b0-b1c4-575e35b3868e.png)

**Comment by GBirkin** [comment]
Same problem, seems the problem happens if the tweet or OP handler or name have a 'special character' like non-latin alphabet characters, or unicode characters (in this case the OP's name had a 'Ø' on it)

![image](https://user-images.githubusercontent.com/34953527/170292369-aa972f87-2a9d-4dc3-a1b5-ef5e4b9cfb1f.png)

**Comment by Choooks22** [comment]
> Same problem, seems the problem happens if the tweet or OP handler or name have a 'special character' like non-latin alphabet characters, or unicode characters (in this case the OP's name had a 'Ø' on it)

Not the case, here's a tweet that has no unicode characters anywhere

![image](https://user-images.githubusercontent.com/49726759/170295409-ecb2f5be-1c9e-4982-88ed-535a14df0d91.png)

I've had the same [issue](https://github.com/Choooks22/sauce-jar/issues/6#issuecomment-1137419328), and the solution was to check if the embed had an author instead of just checking if there's an embed or not

**Comment by Sn0wCrack** [comment]
Thanks @Choooks22 I've deployed this now, appreciate the PR.
